name = "camper-pack"
compatibility_date = "2024-12-30"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "CAMPER_DB"
database_name = "camper-pack"
database_id = "ccdf078f-3766-4eeb-ad1f-d8986c2a4c7a"

# Environment variables are set in Cloudflare Dashboard as secrets
